//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dtnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtnSinhVien
    {
        public string DtnMaSV { get; set; }
        public string DtnHoSV { get; set; }
        public string DtnTenSV { get; set; }
        public Nullable<System.DateTime> DtnNgaySinh { get; set; }
        public Nullable<bool> DtnPhai { get; set; }
        public string DtnPhone { get; set; }
        public string DtnEmail { get; set; }
        public string DtnMaKH { get; set; }
    
        public virtual DtnKhoa DtnKhoa { get; set; }
    }
}
