//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtnK22CNT4Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DtnCategory
    {
        [Display(Name ="Mã loại")]
        public int DtnID { get; set; }
        [Display(Name = "Tên danh mục")]
        public string DtnCateName { get; set; }
        [Display(Name = "trạng thái")]
        public Nullable<bool> DtnStatus { get; set; }
    }
}
