//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtnK22CNT4Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtnProduct
    {
        public string Dtnid2210900052 { get; set; }
        public string DtnProName { get; set; }
        public Nullable<int> DtnQty { get; set; }
        public Nullable<double> DtnPrice { get; set; }
        public Nullable<int> DtnCateId { get; set; }
        public Nullable<bool> DtnActive { get; set; }
    }
}
